/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 16.12.2025 00:01:51

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 8
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10128;
#else
constexpr int kTensorArenaSize = 9104;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0030484069138765335, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data5[2] = { -1, 400, };
const TfArray<1, int> tensor_dimension5 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data6[3] = { -985, 1473, -448, };
const TfArray<1, int> tensor_dimension6 = { 1, { 3 } };
const TfArray<1, float> quant6_scale = { 1, { 0.00013768248027190566, } };
const TfArray<1, int> quant6_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data7[3*400] = { 
  29, 44, 45, -17, 7, 20, 61, 6, 5, 40, 28, 21, 25, -36, 26, -47, -3, -13, 0, -8, -42, 13, 34, 7, -10, -4, 20, -24, -2, -24, 13, -36, -5, -11, -37, -21, -12, -29, -4, 6, -22, -4, 2, 6, 13, -34, 29, -36, 10, -8, -17, -20, -2, -25, 13, 5, 21, -9, 36, -22, 6, -18, 3, -39, 25, -2, -19, 11, -13, 19, 36, -4, 4, 27, 16, 40, 3, 4, 40, -2, 10, -11, 32, 8, -8, -11, 56, 18, 13, 42, 22, 22, 29, 12, 39, -45, 11, -3, 17, -3, -41, 30, 14, 11, 16, -4, 5, 3, 6, 5, -2, -19, -2, 26, 1, -19, -7, 3, -28, 12, 19, -7, 14, -24, -17, 5, 25, -64, 20, 6, -23, 18, -8, -18, 5, -14, 32, -12, 34, 15, 3, 13, 1, -34, -23, 14, -13, 17, -18, -19, 36, -30, 3, -11, 8, 11, 23, -59, 4, -13, 18, -15, -37, 21, -36, 2, 6, -16, 1, 9, -6, -8, 8, -33, 11, -30, -12, -16, 10, 14, 31, -18, -2, 4, 1, 24, 14, 4, -8, -20, 12, -22, 42, 14, -3, 16, 3, 1, 22, 19, 0, 33, 28, -10, 38, -31, 15, -2, 19, -14, -21, 13, 5, -24, -8, -1, 29, 12, -5, -7, 6, -17, 28, -12, -11, -15, -6, -10, -4, -17, 11, -16, 17, 14, -11, -9, -14, 8, -7, -25, 9, 10, -23, -6, 44, -11, 7, 21, 12, 11, 16, 12, 23, 6, 1, -35, 18, 10, 37, 27, -22, -4, 46, 20, 2, 36, 43, 42, 37, 15, 21, -21, -4, 1, 14, 10, -51, -24, 46, -14, 12, -3, 4, 3, 18, -2, -10, -18, -25, -3, -11, -24, -53, -36, 20, 8, 14, -4, -10, -1, 0, -19, 14, -26, -26, -34, -3, 16, -33, 3, 16, 18, 13, 38, 4, -13, 3, -26, -1, -53, -5, -12, 12, 47, -16, 16, 24, 28, 27, 9, 31, 7, 35, -27, 3, -48, -27, 12, -29, 64, -29, -5, 49, 21, 57, 23, 33, 44, 38, -34, 15, -43, -14, -19, -25, 26, 0, 5, 26, 13, 23, 16, 32, 29, 20, -49, -2, -1, -2, 2, 11, 21, 59, 28, 27, 12, 29, 35, 19, 33, -7, -10, 0, -48, 13, 13, 8, 31, 29, 5, 24, 10, 28, 30, 33, 11, 20, -6, 11, -35, 
  -26, -51, -78, 37, -105, -58, -14, -82, -12, -18, -21, -46, -38, -23, -25, 112, 1, -28, -66, 52, 0, -44, -9, -35, -4, -15, 10, 8, -21, -52, 8, 18, 8, -28, -43, 28, 7, -49, -29, -20, -5, -20, -32, -22, -32, -48, -27, 60, -16, -23, -18, 29, 18, -20, -22, -37, -17, -16, -34, -20, -3, -15, -14, 45, -3, -5, -10, 36, -14, -18, 8, -19, -15, -1, -10, 9, -8, -24, -32, 20, -29, -12, -42, 32, 6, -14, -16, -7, 10, -13, -23, -3, -24, 19, -23, 48, -39, -36, -14, 55, -41, -36, -31, -32, -18, -25, -35, -11, -27, -32, -30, 56, -34, -13, 5, 33, -17, -21, 1, -24, -19, 0, -33, -35, -14, -28, -29, 19, -40, -12, -30, 33, -56, -31, -22, -45, -30, -31, -34, -7, 0, -58, 1, 48, -30, -1, 13, 23, -33, -19, -17, -37, -20, -10, -27, -12, -42, -50, -21, 62, -15, -1, -27, 24, 25, -29, 4, -34, -32, -4, -35, 2, -6, -32, 4, 56, -3, -42, -16, 53, -13, 0, 8, -28, -9, -3, -4, -34, -30, -25, -16, 57, -30, -26, -31, -3, 16, -35, -19, 3, -20, -28, -6, 1, -24, -29, 11, 31, 1, -50, -52, 12, -12, -34, -33, -33, -19, 9, -18, -8, -22, -46, -22, 61, -27, -7, -28, 49, 12, -33, 7, -41, 11, -8, -6, 2, 7, -51, 13, 42, -20, -20, -26, 60, -20, -35, 4, -3, -27, -32, 6, 9, 3, -33, -20, 36, 2, -36, -47, 19, -44, -45, -13, -5, -4, -8, -28, 7, -33, -42, 4, 55, -19, 5, -34, 34, -6, -32, -24, -46, 1, 10, -10, -10, -17, -27, -15, 19, -10, -12, 7, 15, -45, -21, -25, -26, -9, -32, -1, -28, -19, -48, -22, 42, -10, 7, -36, -3, -29, -44, -27, -60, -14, -10, -32, 1, -41, -67, -33, 83, -12, -7, -57, 30, -15, -28, -17, -41, -16, 5, -38, -37, -40, -41, -10, 42, -20, -33, 11, -13, -28, -25, -22, -13, -24, -23, -15, -4, -45, -44, -15, 33, -22, -4, -18, -11, -15, -10, -24, -32, -33, -17, -46, -27, -6, -42, -22, 39, -36, -41, -63, 0, -112, -80, -63, -61, -19, -26, -76, -19, -41, -94, 16, 64, -39, -31, -86, 1, -73, -90, -56, -95, -54, -42, -65, -57, -18, -127, 0, 32, 
  -21, -2, 21, -31, -19, -10, -66, -18, -11, -18, 13, -36, -16, 39, -15, -69, 1, 13, 16, 17, 42, 36, 3, -13, -30, 10, 7, 26, 0, 15, 0, -18, -3, 39, 41, 9, 30, 23, -1, 35, 16, -33, 14, 25, 25, 34, -15, -57, 3, 4, 2, -22, 14, -1, -25, 17, -12, 9, 7, 17, 3, 6, -28, -31, 3, 36, 23, -12, 1, -13, -43, 4, -44, -39, -54, -25, 3, 26, -45, -49, -25, -6, 19, -68, 13, -10, -63, -15, -37, -2, -46, -30, -17, 11, -28, -24, -21, 5, -1, 0, 26, 22, -16, 11, 19, -20, -21, -5, -8, 6, 14, -7, 0, -20, 26, -35, 6, 34, 38, 10, 21, -21, 3, -2, -14, -10, -18, -35, 14, -3, 16, -26, 50, 0, 8, 11, -27, -5, -35, -6, 23, -1, 2, -54, 22, -6, 20, -2, 46, 22, 12, 4, -19, 18, 12, -19, -11, 42, 11, -72, 25, 17, 32, -3, 23, 24, 2, 19, 20, -24, 0, 23, 4, 19, -11, -41, 17, 6, 30, -16, -20, -5, 3, 21, -10, -20, -17, 13, 11, 31, 18, -29, 5, 11, 11, -14, 34, 27, 3, 28, 5, -4, -15, 8, -16, 21, -14, -50, -37, 1, 38, -15, 11, 35, -6, -4, 5, -19, 1, 16, 22, 31, -15, -43, -14, 35, 31, -3, -11, 26, -12, 2, 28, -10, 33, 40, 3, 12, -29, -44, -5, 47, -14, -28, -11, 10, -17, -17, 8, 3, -16, 29, 3, -1, -15, -18, -31, 4, -9, -16, 28, 10, -61, -3, -32, -6, -50, -26, -28, -36, -28, -40, -10, -7, 8, -57, 36, 19, -41, -13, -51, -28, -8, -33, -15, 2, -17, -18, 5, 26, 18, -25, 23, -1, -26, 32, -14, -29, 11, -24, -8, 65, -16, 2, 31, 19, 19, -23, -2, 34, 3, 27, 3, -25, -26, -9, 0, 51, 19, -21, 35, 21, 16, -71, 29, -3, -38, 25, -20, -15, -41, -36, 4, 25, 4, 18, 32, 9, 12, -54, 28, 9, -38, 20, -60, -54, -38, -44, 4, 38, 18, 5, 19, 23, 38, -55, 36, 13, -6, 4, -44, -36, -18, -31, -2, 54, -5, -42, 16, 46, 43, -29, -17, 27, -27, 31, -14, -17, -30, 12, -12, 56, -16, -13, -41, 10, 18, -32, -56, -13, -27, -12, -31, -6, -23, -11, 8, 20, 0, 28, 
};
const TfArray<2, int> tensor_dimension7 = { 2, { 3,400 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0050650765188038349, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant6_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data8[16] = { -625, -1471, -360, 1613, 793, 118, -2345, -854, -2327, -1932, -1487, -1211, -1487, 132, -2009, 4060, };
const TfArray<1, int> tensor_dimension8 = { 1, { 16 } };
const TfArray<16, float> quant8_scale = { 16, { 6.9932393671479076e-05, 4.5716522436123341e-05, 4.7070399887161329e-05, 6.3891078752931207e-05, 5.5104475904954597e-05, 6.0575734096346423e-05, 5.0311638915445656e-05, 6.3152234361041337e-05, 5.3146352001931518e-05, 6.3352592405863106e-05, 5.1524653827073053e-05, 5.2942879847250879e-05, 4.6161851059878245e-05, 6.9810994318686426e-05, 4.57682108390145e-05, 6.4130770624615252e-05, } };
const TfArray<16, int> quant8_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[16*1*3*8] = { 
  /* [0][0][][] */ 22,50,127,54,-4,19,14,22, 17,32,32,-13,-65,42,65,-73, 31,48,67,6,-36,-13,76,-3, 
  /* [1][0][][] */ -45,95,1,42,27,-84,17,34, -39,-6,-3,-36,127,94,111,96, 74,39,116,-121,-21,-111,-6,-29, 
  /* [2][0][][] */ -73,112,6,32,53,-4,68,61, 5,60,108,71,85,-84,82,127, -73,106,122,-65,19,13,127,12, 
  /* [3][0][][] */ 127,-51,-20,5,29,8,-76,55, 77,-68,-55,88,-26,-12,-67,30, 29,-24,-66,-4,7,11,21,48, 
  /* [4][0][][] */ -50,-15,0,-56,-29,-68,87,39, -111,13,19,-15,13,101,105,40, -41,127,97,3,-23,125,33,65, 
  /* [5][0][][] */ -51,85,42,59,33,-77,-9,90, -62,82,-17,-12,91,84,-37,20, -51,127,77,51,53,28,-33,87, 
  /* [6][0][][] */ 115,20,17,127,-111,38,16,43, 40,-32,17,-28,-63,45,-11,74, -75,-43,-56,112,-74,72,-93,-47, 
  /* [7][0][][] */ -12,71,-4,-45,-73,97,112,62, 14,72,66,98,52,89,117,91, 5,12,-29,7,73,40,127,40, 
  /* [8][0][][] */ 40,-65,25,94,-32,10,33,69, -52,-59,-114,89,27,5,-127,113, 33,-46,16,65,-37,65,-77,6, 
  /* [9][0][][] */ 127,-44,6,66,-84,54,31,30, 15,-30,-34,-35,-37,47,-30,12, -23,-43,-55,75,-80,53,-45,57, 
  /* [10][0][][] */ 1,-25,-55,75,-27,10,29,6, -105,-47,-36,32,-75,-17,-99,60, -71,1,-68,95,-104,90,-67,127, 
  /* [11][0][][] */ -45,46,-79,127,76,65,-73,5, -17,-24,-6,44,79,-24,-31,73, 11,-2,-72,88,-96,-40,-118,-2, 
  /* [12][0][][] */ -92,18,-68,127,-61,-19,97,9, 44,-33,-92,-12,-116,75,-28,-11, 47,21,58,50,9,-80,-92,71, 
  /* [13][0][][] */ -27,42,51,-31,-30,53,26,-18, -14,96,44,5,-19,-54,5,-42, -48,69,127,6,88,-43,-16,73, 
  /* [14][0][][] */ 83,1,47,-1,-8,75,43,-50, 9,68,65,48,-13,23,65,-64, 119,-91,-5,127,15,-70,-36,-77, 
  /* [15][0][][] */ 96,46,11,-103,32,-71,-103,-16, 43,7,75,-85,27,-57,-28,-13, -9,-69,62,-127,-48,-27,-30,-24, 
};
const TfArray<4, int> tensor_dimension9 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant9_scale = { 16, { 0.0042161992751061916, 0.0027562328614294529, 0.0028378576971590519, 0.003851970424875617, 0.0033222292549908161, 0.0036520895082503557, 0.0030332708265632391, 0.0038074259646236897, 0.0032041748054325581, 0.0038195054512470961, 0.0031064031645655632, 0.003191907424479723, 0.0027830817271023989, 0.0042088800109922886, 0.0027593492995947599, 0.0038664212916046381, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[8] = { 9449, -1396, 570, -7655, 2317, -3654, -3384, -2723, };
const TfArray<1, int> tensor_dimension10 = { 1, { 8 } };
const TfArray<8, float> quant10_scale = { 8, { 1.5527475625276566e-05, 1.0028808901552111e-05, 8.7148737293318845e-06, 1.0385861969552934e-05, 9.6129069788730703e-06, 1.1712996638379991e-05, 9.3251810540095903e-06, 8.9649975052452646e-06, } };
const TfArray<8, int> quant10_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[8*1*3*40] = { 
  /* [0][0][][] */ -6,68,17,-10,-51,-64,-38,-60,-82,-46,-1,-68,-1,-60,-55,-13,-36,-22,-11,-84,-4,9,19,7,-22,-4,-24,-68,-16,-56,-79,12,-6,-17,33,-24,-32,9,77,75, 4,-1,-50,11,-27,-56,-26,-24,-67,-2,26,4,-89,10,-7,10,23,9,-16,-6,-63,17,1,-27,-80,-56,-5,-40,13,-35,-51,-1,-66,-54,-31,-73,-78,-45,15,109, 19,-22,17,-43,26,-71,-127,-31,-54,33,-39,-39,-13,-40,-44,-6,-22,-8,22,-42,-3,-16,-11,-1,-62,-40,-67,-30,-22,-31,-52,-52,-16,-33,-70,-101,-101,79,102,113, 
  /* [1][0][][] */ -35,-102,-74,-11,-96,35,-39,75,14,28,25,5,101,-25,91,28,-39,-12,47,38,21,-28,11,24,21,-48,-45,6,-39,0,-2,-73,-18,43,40,52,-38,-45,-20,-107, 81,-39,-93,-29,-47,55,70,68,30,4,32,33,89,-18,-17,69,32,-29,-48,-33,28,65,-40,-3,-46,-17,17,1,-18,39,-14,2,9,84,37,13,-16,-6,-18,-104, 89,-93,-61,-92,-95,32,62,17,-31,46,-4,94,127,-6,29,22,9,46,36,-36,-32,13,-65,38,45,53,-23,93,-29,-56,38,-22,35,-33,6,72,57,15,-54,-19, 
  /* [2][0][][] */ 21,43,-98,-59,-69,-17,98,69,-5,42,67,-14,87,-35,-16,73,54,-52,27,24,79,8,5,22,26,-68,-40,-22,-1,-105,-86,-29,-122,-25,19,-101,-21,-84,-56,-75, 1,-31,-38,-72,-13,37,92,-15,73,-57,98,-20,18,40,93,51,-63,-50,37,55,15,60,-36,5,-24,49,-23,41,-62,-95,-74,2,-127,-45,-65,-92,-126,-7,-104,-97, 8,-107,-101,-63,4,5,112,91,65,-31,-43,21,73,45,31,54,-61,-73,61,-64,38,30,-61,22,72,-84,17,-1,2,18,-9,-60,-40,-111,8,-83,-50,25,-74,-104, 
  /* [3][0][][] */ -84,67,80,23,116,-1,44,11,51,-62,-25,-74,-49,0,-4,-19,42,0,38,34,51,57,73,42,23,74,62,-63,90,64,65,71,77,51,36,45,12,34,-13,120, -80,53,82,50,95,46,43,-29,52,29,-66,-46,-65,-64,21,-66,33,24,14,45,52,34,28,46,2,-11,50,-49,49,26,92,96,62,25,-22,-1,29,-9,97,52, 16,69,127,25,87,50,1,-4,-56,0,27,-82,-97,-14,-88,-19,-10,-27,-10,69,-34,35,-15,2,-28,26,59,3,86,-1,91,-1,35,29,-20,26,57,-19,-4,64, 
  /* [4][0][][] */ 67,-73,-81,9,-89,-37,6,49,1,16,-11,73,72,32,-25,52,-18,-15,-59,-61,-43,-56,-66,26,-13,-8,16,66,49,-17,-16,47,-9,16,81,0,8,71,-28,-29, 52,-46,-28,-96,-80,-43,72,-41,3,-3,23,66,16,33,-49,-29,-43,14,-4,-61,-68,-7,8,56,10,49,14,-12,-7,32,-59,66,-46,-52,78,54,-13,22,-75,-71, 65,-112,-127,-63,-80,-47,56,26,-20,-8,8,88,81,51,-65,15,-63,-27,-12,-28,-27,-49,-36,-26,14,-66,-55,-5,-38,26,33,-50,59,31,-20,64,62,58,-19,-119, 
  /* [5][0][][] */ -58,76,67,92,87,42,-2,28,8,28,-46,18,-28,2,-54,-36,-76,14,19,57,-4,1,68,-75,-13,-29,33,11,-25,70,-40,61,22,-23,-2,-11,-19,-43,47,32, -64,38,116,124,104,33,-5,-1,-5,-23,-64,-60,-31,19,-42,-17,-4,17,88,73,66,9,65,46,-24,59,8,54,53,60,20,29,0,48,-49,-1,42,83,31,46, 38,36,127,74,81,64,19,12,50,58,19,3,-29,26,-47,3,34,-4,35,-31,54,63,6,30,-7,1,64,39,28,13,37,65,3,-60,-62,-35,20,-23,46,112, 
  /* [6][0][][] */ 78,-1,-76,-42,-60,-36,-3,-30,-52,-63,-14,48,20,33,39,-20,-12,94,43,31,3,69,40,79,21,14,127,88,20,-48,-17,-34,53,-39,-36,35,-31,70,-76,-102, 19,-121,-40,-80,-100,42,62,47,18,20,-24,79,-44,21,58,-55,-37,-54,67,57,-26,-54,-19,-12,-72,21,13,74,-58,-78,10,27,-81,-8,-78,23,48,21,-124,-120, 42,-91,-127,-82,-108,-72,41,5,78,62,-40,-11,21,-34,-33,-55,44,-40,17,-31,-26,-83,23,-3,2,-36,-50,20,-31,-17,-81,-36,-34,-8,-48,32,-13,-77,-127,-90, 
  /* [7][0][][] */ 30,89,122,116,127,69,-59,32,-41,-47,42,-64,28,-62,-19,14,15,81,-22,-9,-16,16,-53,-28,52,31,34,51,96,106,25,6,95,110,-3,-37,49,4,68,42, -55,79,37,60,1,-8,12,50,4,15,35,-69,9,-22,-80,-49,-37,-12,-4,-64,-21,12,42,11,7,31,8,50,77,31,-9,32,102,83,57,31,38,50,27,80, -20,15,23,39,-3,3,-26,5,-21,25,-24,-9,-93,-6,2,37,32,51,36,-23,-27,26,47,32,-46,110,46,50,19,86,66,84,-10,26,-48,24,-36,-26,72,89, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant11_scale = { 8, { 0.0050936359912157059, 0.00328985252417624, 0.0028588289860635996, 0.003406980074942112, 0.0031534198205918074, 0.0038423335645347834, 0.0030590342357754707, 0.0029408794362097979, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const TfArray<4, int> tensor_dimension12 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension13 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant13_scale = { 1, { 0.016586596146225929, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension14 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension15 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant17_scale = { 1, { 0.027182705700397491, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,16 } };
const TfArray<2, int> tensor_dimension20 = { 2, { 1,400 } };
const TfArray<2, int> tensor_dimension21 = { 2, { 1,3 } };
const TfArray<1, float> quant21_scale = { 1, { 0.3786638081073761, } };
const TfArray<1, int> quant21_zero = { 1, { 48 } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&quant21_zero, 0 };
const TfArray<1, float> quant22_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 12 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 12,11,10 } };
const TfArray<1, int> outputs1 = { 1, { 13 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 13,2 } };
const TfArray<1, int> outputs2 = { 1, { 14 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 14 } };
const TfArray<1, int> outputs3 = { 1, { 15 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 15,3 } };
const TfArray<1, int> outputs4 = { 1, { 16 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 16,9,8 } };
const TfArray<1, int> outputs5 = { 1, { 17 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 17,4 } };
const TfArray<1, int> outputs6 = { 1, { 18 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 18 } };
const TfArray<1, int> outputs7 = { 1, { 19 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 19,5 } };
const TfArray<1, int> outputs8 = { 1, { 20 } };
const TfLiteFullyConnectedParams opdata9 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs9 = { 3, { 20,7,6 } };
const TfArray<1, int> outputs9 = { 1, { 21 } };
const TfLiteSoftmaxParams opdata10 = { 1 };
const TfArray<1, int> inputs10 = { 1, { 21 } };
const TfArray<1, int> outputs10 = { 1, { 22 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 1200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension13, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension14, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension15, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension17, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[11] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 23, };
const size_t tflNodes_subgraph_index[] = {0, 11, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  22, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_843533_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 23;
  for (size_t i = 0; i < 23; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_843533_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_843533_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_843533_4_invoke() {
  for (size_t i = 0; i < 11; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_843533_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
